// frontend/src/components/HelloWorld.jsx
import React, { useEffect, useState } from 'react';

function HelloWorld({ msg }) {
  const [count, setCount] = useState(0);

  useEffect(() => {
    const apiCall = () => {
      fetch('/api/counter')
        .then((response) => response.json())
        .then((data) => setCount(data.counter));
    };
    apiCall();
    const interval = setInterval(apiCall, 1000);
    return () => clearInterval(interval);
  }, []);

  return (
    <section className="py-5 text-center container">
      <div className="row py-lg-5">
        <div className="col-lg-6 col-md-8 mx-auto">
          <h1 className="fw-light">{msg}</h1>
          <p className="lead text-muted">
            The count is: {count}.
          </p>
        </div>
      </div>
    </section>
  );
}

export default HelloWorld;

// frontend/src/components/HelloWorld.vue
<script setup>
import { ref } from 'vue'

defineProps({
  msg: String
})

const count = ref(0);
const apiCall = () => {
    fetch("/api/counter")
        .then((response) => response.json())
        .then((data) => count.value = data.counter);
}

setInterval(apiCall, 1000);
</script>

<template>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light">{{ msg }}</h1>
                <p class="lead text-muted">
                    The count is: {{ count }}.
                </p>
            </div>
        </div>
    </section>
</template>

<style scoped>
</style>
